export default {
    SUCCESS: 'SUCCESS',
    ALREADY_EXISTS: 'ALREADY_EXISTS',
    FAILED: 'FAILED',
    VERIFICATION_PENDING: 'VERIFICATION_PENDING',
    INVALID_TOKEN: 'INVALID_TOKEN',
    UNAUTHORIZED: 'UNAUTHORIZED',
    INVALID_CODE: 'INVALID_CODE',
};